### ISSUE TITLE
Manipulating the e.data.date string to suit...

### ISSUE THREAD

**Issue by richgcook** [ericwenn/kalendar#2]
I was wondering if it's possible to customise the `e.data.date` to a string output that's more suited to my needs. Currently, `e.data.date`, for example, would output as `Thu Jun 2012 2014 2000:00:00 GMT+0100 (BST)` but ideally I'd like to to replicate the event start and end date input of `20140607`.

I'm planning on adding a callback using `onDayShow` so if a date with an event is clicked, it takes you to a page where it lists the event.

```
onDayShow: function(e) {
     window.location.href = 'http://www.mywebsite.com/events/' + e.data.date;
}
```

So would like the URL to be, for example, http://www.mywebsite.com/events/20140607

Thanks in advance,
R

**Comment by ericwenn** [comment]
`e.data.date` is a [date object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date).

So you could use `e.data.date.getUTCDate()` to get the month for example.

Beware that you will have to format the output to accommodate single digit numbers.
For example 2014112 could be both 2014-11-2 and 2014-1-12 while 20141102 can only be one.

Cheers

**Comment by richgcook** [comment]
Thanks.

`e.data.date.getUTCDate()` gets the month, great, but to get the desired output of `20141102`, for example, which includes year, month and date, there doesn't seem to be a getter method...

**Comment by richgcook** [comment]
I managed it with this below, but do let me know if there's a better way.

```
Date.prototype.GetCustomFormat = function() {
    return this.getFullYear()+''+getInTwoDigitFormat(this.getMonth()+1)+''+getInTwoDigitFormat(this.getDate());
};
function getInTwoDigitFormat(val) {
    return val < 10 ? '0' + val : val;
}

e.data.date.GetCustomFormat();
```
